## the list of groups for which motion planning can be performed
groups: 
  - arm_cartesian
  - arm

## the planner configurations; each config must have a type, which specifies
## the planner to be used; other parameters can be specified as well, depending 
## on the planner

arm:
  planner_type: JointPlanner
  planner_configs:
    - SBLkConfig1 
    - LBKPIECEkConfig1
  kinematics_solver: pr2_arm_kinematics/PR2ArmKinematicsPlugin  # DIAMONDBACK TODO
#  redundancy:
#    name: r_upper_arm_roll_joint
  tip_name: katana_gripper_tool_frame
  root_name: katana_base_link
  projection_evaluator: joint_state

arm_cartesian:
  parent_frame: katana_base_link
  physical_group: arm
  planner_type: RPYIKTaskSpacePlanner
  manifolds:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
#    - r_upper_arm_roll_joint
  x:
    type: Linear
    min: -2.0
    max: 2.0
  y:
    type: Linear
    min: -2.0
    max: 2.0
  z:
    type: Linear
    min: -2.0
    max: 2.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1 
    - LBKPIECEkConfig1
  kinematics_solver: pr2_arm_kinematics/PR2ArmKinematicsPlugin  # DIAMONDBACK TODO
  tip_name: katana_gripper_tool_frame
  root_name: katana_base_link
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001
  
planner_configs:
  SBLkConfig1:
    type: kinematic::SBL

  LBKPIECEkConfig1:
    type: kinematic::LBKPIECE

publish_diagnostics: true