## This file should be loaded under ompl_planning

## the list of groups for which motion planning can be performed
group_list:
  arm

## the planner configurations; each config must have a type, which specifies
## the planner to be used; other parameters can be specified as well, depending 
## on the planner

planner_configs:
  
  armIKConfig1:
    type: GAIK

  KPIECEkConfig1:
    type: kinematic::KPIECE
    projection: 0 1
    celldim: 1 1
    range: 0.5

  RRTkConfig2:
    type: kinematic::RRT
    range: 0.75

  SBLkConfig2:
    type: kinematic::SBL
    projection: 5 6
    celldim: 0.1 0.1
  
  KPIECEkConfig2l:
    type: kinematic::KPIECE
    projection: link katana_gripper_tool_frame
    celldim: 0.1 0.1 0.1

  LBKPIECEkConfig2l:
    type: kinematic::LBKPIECE
    projection: link katana_gripper_tool_frame
    celldim: 0.1 0.1 0.1

## the definition of the planners that go in each group
groups:
  - name: arm
    planner_configs:
      RRTkConfig2 SBLkConfig2 KPIECEkConfig1 KPIECEkConfig2l LBKPIECEkConfig2l armIKConfig1

