arm:
  tip_name: katana_gripper_tool_frame
  #tip_name: katana_motor5_wrist_roll_link
  root_name: katana_base_link
  kinematics_solver: katana_openrave_kinematics/KatanaKinematicsPlugin
  
#use_collision_map: true
#default_robot_padding: 0.02
#link_padding:
#  - link: arm 
#    padding: .02
    
use_collision_map: false
collision_map_safety_timeout: 10000.0
joint_states_safety_timeout: 1.0
tf_safety_timeout: 10.0
default_robot_padding: 0.02
link_padding:
  - link: right_arm 
    padding: .02