cloud_sources:
  - name: tilt_scan_cloud_filtered
    # take every nth frame (1 is no discards)
    frame_subsample: 30
    # take every nth point from the frames you do process
    point_subsample: 2 
    sensor_frame: kinect_depth

