min_sensor_dist: .05
self_see_default_padding: .02
self_see_default_scale: 1.0
self_see_links:
  - name: katana_internal_controlbox_link 
  - name: katana_base_link
  - name: katana_motor1_pan_link
  - name: katana_motor2_lift_link
    padding: 0.06
  - name: katana_motor3_lift_link
  - name: katana_motor4_lift_link
  - name: katana_motor5_wrist_roll_link
  - name: katana_gripper_link
  - name: katana_l_finger_link
  - name: katana_r_finger_link
