service_type: FilterJointTrajectory
filter_chain:
#  - 
#    name: numerical_differentiation
#    type: NumericalDifferentiationSplineSmootherFilterJointTrajectory
#  -
#    name: linear_spline_velocity_scaler
#    type: LinearSplineVelocityScalerFilterJointTrajectory
  -
    name: cubic_spline_velocity_scaler
    type: CubicSplineVelocityScalerFilterJointTrajectory
  -
    name: katana_trajectory_filter
    type: katana_trajectory_filter/KatanaTrajectoryFilterFilterJointTrajectory
  - 
    name: clamped_cubic_spline_smoother
    type: ClampedCubicSplineSmootherFilterJointTrajectory
